# Generated by Django 5.0.6 on 2024-06-05 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_transaction_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="account",
        ),
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
